nelmio/NelmioSecurityBundle

- README.md
I also updated the date reference.
> add link to caniuse for HSTS in the README

- CHANGELOG.md
- DependencyInjection/Configuration.php
- DependencyInjection/NelmioSecurityExtension.php
- EventListener/XssProtectionListener.php
- README.md
- Resources/config/xss_protection.yml
- Tests/Listener/XssProtectionListenerTest.php
See http://blogs.msdn.com/b/ieinternals/archive/2011/01/31/controlling-the-internet-explorer-xss-filter-with-the-x-xss-protection-http-header.aspx
> Add XSS protection

- EventListener/ContentSecurityPolicyListener.php
I think I did something wrong while rebasing.... :/ Here's the fix
> Fix content security policy listener

- CHANGELOG.md
- ContentSecurityPolicy/DirectiveSet.php
- DependencyInjection/Configuration.php
- EventListener/ContentSecurityPolicyListener.php
- Tests/DependencyInjection/ConfigurationTest.php
For the record we updated the configuration format in #33
> Drop Content-Security-Policy legacy configuration

- ContentSecurityPolicy/ContentSecurityPolicyParser.php
- ContentSecurityPolicy/DirectiveSet.php
- DependencyInjection/Configuration.php
- README.md
- Tests/ContentSecurityPolicy/DirectiveSetTest.php
- Tests/DependencyInjection/ConfigurationTest.php
- Tests/Listener/ContentSecurityPolicyListenerTest.php
It was definitely a wrong approach. Boolean nodes are much better
> Fix new CSP level 2 boolean directives

- EventListener/ContentSecurityPolicyListener.php
> Better fix for CSP listener priority

- ContentSecurityPolicy/DirectiveSet.php
- DependencyInjection/Configuration.php
- README.md
- Tests/ContentSecurityPolicy/DirectiveSetTest.php
This would ease a lot testing new policies
> Move level1_fallback configuration from main csp to directives collection

- CHANGELOG.md
- ContentSecurityPolicy/DirectiveSet.php
- ContentSecurityPolicy/PolicyManager.php
- DependencyInjection/Configuration.php
- DependencyInjection/NelmioSecurityExtension.php
- EventListener/ContentSecurityPolicyListener.php
- README.md
- Resources/config/csp.yml
- Resources/config/csp_legacy.yml
- Tests/ContentSecurityPolicy/DirectiveSetTest.php
- Tests/Listener/ContentSecurityPolicyListenerTest.php
- UserAgent/UAParserUserAgentParser.php
- UserAgent/UserAgentParserInterface.php
- composer.json
As suggested on https://twitter.com/romainneutron/status/722409052173705218 and in https://github.com/twitter/secureheaders/blob/83a564a235c8be1a8a3901373dbc769da32f6ed7/lib/secure_headers/headers/policy_management.rb#L97 It's probably a good idea to add such feature.
This is the early work, it needs to finish configuration
> Adjust CSP per user agent

- CHANGELOG.md
- DependencyInjection/Configuration.php
- README.md
- Tests/Listener/ClickjackingListenerTest.php
> Fix ALLOW-FROM implementation

- README.md
> Fix typos and style in README.md

- DependencyInjection/Configuration.php
- DependencyInjection/NelmioSecurityExtension.php
- README.md
| Q | A |
| --- | --- |
| Branch? | "master" |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
> [WIP] Add option to easily enable or disable CSP

- Twig/Node/CSPNode.php
> Fix Twig 2 compatibility

- EventListener/AbstractContentTypeRestrictableListener.php
- EventListener/ClickjackingListener.php
- EventListener/ContentSecurityPolicyListener.php
Introduce proper constructor for a better contract in the base class.
> Cleanup content type listener

- .travis.yml
- composer.json
> Adding Symfony4 support

- DependencyInjection/Compiler/CspReportFilterCompilerPass.php
- NelmioSecurityBundle.php
The compiler pass works but is not actually added to the bundle.
> Actually add compiler pass

- ContentSecurityPolicy/DirectiveSet.php
Hi,
how about adding support for `worker-src` (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src)?
> CSP 3: add "worker-src"

- composer.json
This modification aligns the dev-*master alias with the current version in the master branch
> master branch refers to v2.5

- ContentSecurityPolicy/PolicyManager.php
- Tests/ContentSecurityPolicy/DirectiveSetTest.php
The worker-src directive was added but did not pass the PolicyManager. The worker-src directive has been added to the level3 directives.
> Fix for worker-src

- .travis.yml
- EventListener/EncryptedCookieListener.php
- EventListener/FlexibleSslListener.php
- EventListener/SignedCookieListener.php
- Session/CookieSessionHandler.php
- Tests/Listener/EncryptedCookieListenerTest.php
- Tests/Listener/SignedCookieListenerTest.php
- composer.json
> Fix deprecations

- ContentSecurityPolicy/ContentSecurityPolicyParser.php
- Tests/ContentSecurityPolicy/ContentSecurityPolicyParserTest.php
Support CSP Level 3 keywords like `report-sample` or `unsafe-hashes`
> Support CSP level 3 keywords

- README.md
It was added in https://github.com/nelmio/NelmioSecurityBundle/pull/191, also I guess https://github.com/nelmio/NelmioSecurityBundle/issues/176 can be closed
> Update Documentation to add report URI for XSS

- DependencyInjection/Compiler/UAParserCompilerPass.php
- DependencyInjection/NelmioSecurityExtension.php
>  Use references instead of definitions 

- composer.json
> depend on `symfony/yaml`

- composer.json
Removed uap-php from suggest as it's actual dependency
> [Closes #214] Removed uap-php from suggest

- ContentSecurityPolicy/DirectiveSet.php
- ContentSecurityPolicy/PolicyManager.php
Support for https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src
> Support for pre fetch

- .gitattributes
- .github/workflows/static-analysis.yml
- composer.json
- phpstan-baseline.neon
- phpstan.neon.dist
- src/ContentSecurityPolicy/PolicyManager.php
- src/Controller/ContentSecurityPolicyController.php
- src/DependencyInjection/NelmioSecurityExtension.php
- src/EventListener/BaseFlexibleSslListener.php
- src/EventListener/ExternalRedirectListener.php
- src/EventListener/FlexibleSslListener.php
- src/EventListener/SignedCookieListener.php
- src/Session/CookieSessionHandler.php
- src/UserAgent/UserAgentParserInterface.php
- tests/ContentSecurityPolicy/Violation/EventTest.php
- tests/ContentSecurityPolicy/Violation/ReportTest.php
- tests/DependencyInjection/CspReportFilterCompilerPassTest.php
I'll rebase when merging https://github.com/nelmio/NelmioSecurityBundle/pull/257 and it should be easy to raise the level.
The errors in the baseline are because supporting Symfony 4 and 5 in `AppKernel`.
> Add PHPStan to CI

- composer.json
- src/UserAgent/UAFamilyParser/PsrCacheUAFamilyParser.php
- src/UserAgent/UserAgentParser.php
- tests/SignerTest.php
- tests/UserAgent/UAFamilyParser/PsrCacheUAFamilyParserTest.php
This should increase a little bit code coverage so we can make further changes
> Increase code coverage

- src/NelmioSecurityBundle.php
- src/Signer.php
- src/Twig/NelmioCSPTwigExtension.php
- src/Twig/Node/CSPNode.php
- src/Twig/TokenParser/AbstractCSPParser.php
- src/Twig/TokenParser/CSPScriptParser.php
- src/Twig/TokenParser/CSPStyleParser.php
- src/UserAgent/UAFamilyParser/PsrCacheUAFamilyParser.php
- src/UserAgent/UAFamilyParser/UAFamilyParser.php
- src/UserAgent/UAFamilyParser/UAFamilyParserInterface.php
- src/UserAgent/UserAgentParser.php
- src/UserAgent/UserAgentParserInterface.php
To not create big PRs, I'll be creating small reviewable PRs
> Add some type declarations - part 1

- src/EventListener/AbstractContentTypeRestrictableListener.php
- src/EventListener/ClickjackingListener.php
- src/EventListener/ContentSecurityPolicyListener.php
- src/EventListener/ContentTypeListener.php
- src/EventListener/ExternalRedirectListener.php
- src/EventListener/FlexibleSslListener.php
- src/EventListener/ForcedSslListener.php
- src/EventListener/ReferrerPolicyListener.php
- src/EventListener/SignedCookieListener.php
- src/EventListener/XssProtectionListener.php
- src/ExternalRedirect/TargetValidator.php
- src/ExternalRedirect/WhitelistBasedTargetValidator.php
- src/Session/CookieSessionHandler.php
- src/Twig/NelmioCSPTwigExtension.php
- tests/Listener/ContentSecurityPolicyListenerTest.php
After this one I'll create another one for `ContentSecurityPolicy`, `DependencyInjection` and `Controller` directories and after that I think we would be able to raise the PHPStan level.
> Add type declarations - part 2

- src/ContentSecurityPolicy/ContentSecurityPolicyParser.php
- src/ContentSecurityPolicy/DirectiveSet.php
- src/ContentSecurityPolicy/NonceGenerator.php
- src/ContentSecurityPolicy/PolicyManager.php
- src/ContentSecurityPolicy/ShaComputer.php
- src/ContentSecurityPolicy/Violation/Event.php
- src/ContentSecurityPolicy/Violation/Filter/BrowserBugsNoiseDetector.php
- src/ContentSecurityPolicy/Violation/Filter/CustomRulesNoiseDetector.php
- src/ContentSecurityPolicy/Violation/Filter/DomainsNoiseDetector.php
- src/ContentSecurityPolicy/Violation/Filter/DomainsRegexNoiseDetector.php
- src/ContentSecurityPolicy/Violation/Filter/Filter.php
- src/ContentSecurityPolicy/Violation/Filter/InjectedScriptsNoiseDetector.php
- src/ContentSecurityPolicy/Violation/Filter/NoiseDetectorInterface.php
- src/ContentSecurityPolicy/Violation/Filter/SchemesNoiseDetector.php
- src/ContentSecurityPolicy/Violation/Log/LogFormatter.php
- src/ContentSecurityPolicy/Violation/Log/LogFormatterInterface.php
- src/ContentSecurityPolicy/Violation/Log/Logger.php
- src/ContentSecurityPolicy/Violation/Report.php
I think there are some methods/code unused, we can take a look at it when increasing PHPStan levels and adding some other plugins.
> Add type declarations - final

- CHANGELOG.md
- ContentSecurityPolicy/Violation/Report.php
related to https://github.com/nelmio/NelmioSecurityBundle/pull/272#pullrequestreview-862362636
> Fix unused code report generation

- src/ContentSecurityPolicy/DirectiveSet.php
- src/ContentSecurityPolicy/NonceGenerator.php
- src/ContentSecurityPolicy/Violation/Filter/CustomRulesNoiseDetector.php
- src/ContentSecurityPolicy/Violation/Filter/DomainsRegexNoiseDetector.php
- src/ContentSecurityPolicy/Violation/Filter/InjectedScriptsNoiseDetector.php
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/NelmioSecurityExtension.php
- src/EventListener/ClickjackingListener.php
- src/EventListener/ForcedSslListener.php
- src/Session/CookieSessionHandler.php
- tests/ContentSecurityPolicy/Violation/ReportTest.php
- tests/Listener/ClickjackingListenerTest.php
- tests/Listener/ContentSecurityPolicyListenerTest.php
- tests/Listener/ContentTypeListenerTest.php
- tests/Listener/ExternalRedirectListenerTest.php
- tests/Listener/ForcedSslListenerTest.php
- tests/Listener/ReferrerPolicyListenerTest.php
- tests/Listener/XssProtectionListenerTest.php
It solves some of the issues found with PHPStan level 7
> Make some comparison stricter

- phpstan-baseline.neon
- phpstan.neon.dist
- src/ContentSecurityPolicy/DirectiveSet.php
- src/ContentSecurityPolicy/Violation/Report.php
- src/Session/CookieSessionHandler.php
- tests/ContentSecurityPolicy/DirectiveSetTest.php
- tests/DependencyInjection/ConfigurationTest.php
There were just a few issues, some of the ignored ones are about specifying all options in CSP config.
> Bump to PHPStan level 9

- src/ContentSecurityPolicy/NonceGenerator.php
- src/ContentSecurityPolicy/NonceGeneratorInterface.php
- src/ContentSecurityPolicy/ShaComputer.php
- src/ContentSecurityPolicy/ShaComputerInterface.php
- src/EventListener/ContentSecurityPolicyListener.php
- src/Twig/NelmioCSPTwigExtension.php
- src/Twig/TokenParser/AbstractCSPParser.php
- src/Twig/TokenParser/CSPScriptParser.php
- src/Twig/TokenParser/CSPStyleParser.php
- tests/Listener/ContentSecurityPolicyListenerTest.php
IMO These classes need interfaces, this will also allow to make `NonceGenerator` and `ShaComputer` `final`.
> Introduce NonceGeneratorInterface and ShaComputerInterface

- phpstan-baseline.neon
see https://github.com/phpstan/phpstan/issues/6508
> Ignore phpstan false positives

- src/DependencyInjection/Configuration.php
I was thinking about adding the path based configuration if I find some time, this PR is about making the configuration class more readable and these new methods could be reusable.
> Extract configuration methods

- phpstan-baseline.neon
- src/EventListener/SignedCookieListener.php
- tests/Listener/SignedCookieListenerTest.php
https://github.com/symfony/http-foundation/blob/439fdfdd344943254b1ef6278613e79040548045/Cookie.php#L315:
```
...
public function getValue(): ?string
...
```
> fix: Added support for cookies with null value

- src/Twig/Node/CSPNode.php
see https://github.com/nelmio/NelmioSecurityBundle/pull/344#discussion_r1660718523
> Fix deprecation with CSPNode yield

- src/EventListener/ExternalRedirectListener.php
- src/EventListener/SignedCookieListener.php
- tests/Listener/ExternalRedirectListenerTest.php
See https://symfony.com/blog/cve-2024-50345-open-redirect-via-browser-sanitized-urls
> Fixed ExternalRedirectListener issue parsing some invalid URLs

- src/Resources/doc/index.rst
Page: https://symfony.com/bundles/NelmioSecurityBundle/current/index.html
> Update index.rst: Updating filename; using consistent report-uri
