- DependencyInjection/Configuration.php
- DependencyInjection/NelmioSecurityExtension.php
- EventListener/ForcedSslListener.php
- README.md
- Resources/config/forced_ssl.yml
- Tests/Listener/ForcedSslListenerTest.php
Quoting from the README addition:
You can also tell the browser to add your site to the list of known HSTS sites, by enabling
`hsts_preload`. Once your site has appeared in the Chrome and Firefox preload lists, then new
users who come to your site will already be redirected to https urls.
> Add configurable HSTS preloading

- Tests/DependencyInjection/ConfigurationTest.php
this seems more accurate, and fixes a bug when trying to remove
the compat_headers option.
When i tried removing the compat_headers option i ended up with:
1) Nelmio\SecurityBundle\Tests\DependencyInjection\ConfigurationTest::testCspReportOnlyDefaultIsFalse
Failed asserting that an array contains 'report_only'.
which seems like a totally unrelated issue.
> use assertArrayHasKey in ConfigurationTest

- EventListener/ContentSecurityPolicyListener.php
- README.md
- Tests/Listener/ContentSecurityPolicyListenerTest.php
I think that there has been enough time for this header to no longer
be necessary.
Let me know if you disagree.
> Remove support for X-Webkit-CSP

- EventListener/ContentSecurityPolicyListener.php
It's a private method, so no BC issues
> Remove unused buildHeaderName

- EventListener/ExternalRedirectListener.php
- ExternalRedirect/TargetValidator.php
- ExternalRedirect/WhitelistBasedTargetValidator.php
- Resources/config/external_redirects.yml
- Tests/Listener/ExternalRedirectListenerTest.php
This makes the target validation a bit more flexible. It is fully backwards-compatible.
> Makes target validation a bit more flexible (BC)

- DependencyInjection/Configuration.php
- EventListener/ContentSecurityPolicyListener.php
In a multi-domain use-case where the CSP should be enforced only on a subset of all domains handled by a single symfony2 installation is sometimes unwanted to have CSP running on all domains.
As an example if an application runs on app.example.net and there is api.example.net for oauth with nelmio apidoc bundle, the apidoc bundle would be broken due inline JS.
This pull requests makes it possible to take out api.example.net from CSP restriction
> add support for host-based CSP settings

- CHANGELOG.md
- DependencyInjection/Configuration.php
- DependencyInjection/NelmioSecurityExtension.php
- EventListener/AbstractContentTypeRestrictableListener.php
- EventListener/ClickjackingListener.php
- EventListener/ContentSecurityPolicyListener.php
- README.md
- Resources/config/clickjacking.yml
- Tests/Listener/ClickjackingListenerTest.php
- Tests/Listener/ContentSecurityPolicyListenerTest.php
This allows restriction on when to add clickjacking and CSP headers. For example, you can specify `text/html` so that these headers are only added in these cases.
>  Add HTTP response's content-type restriction for Clickjacking and CSP headers.

- DependencyInjection/NelmioSecurityExtension.php
Right now, the $forwardAs parameter is set to null, but what we actually want to do here is set $logger to null. This fixes it :)
> fixes the parameter index

- DependencyInjection/NelmioSecurityExtension.php
Hello.
I created this pull request, because it need it in my project.
My use case is:
I'm working on site A, that is a oAuth "client" of site B.
So some HTTP redirections occur from A to B.
We white-listed site B in our configuration, and that is working fine.
But now, I also run a (dev) copy of site B. And so the URL is different.
I don't want to pollute your config.yml with my local endpoint.
Therefore, I already have a parameter in my application to customize
the endpoint of B and I would like to re-use it. But my endpoint
parameter also constain the scheme.
That's why, if in the white-list, an url is provided, we extract
and use only the host part.
What do you think ?
> external_redirects definition can now contains full URL

- EventListener/ContentSecurityPolicyListener.php
This PR adds getter on report and enforce DirectiveSet to allow them to be customize later after initialization.
This is particularly nice in some use case:
- Add extra parameters to the report-uri (a debug token link for instance)
- Extend a security policy directive on a admin backend which needs specific access on some resources
> Allow dynamix CSP configuration

- DependencyInjection/Configuration.php
Symfony config normalize array keys that contains dashes and no underscore, see https://github.com/symfony/symfony/pull/17129 . 
We should not allow normalization on clickjacking keys in rules definition because it breaks the configuration.
For instance, the following conf:
```
paths:
'^/[a-zA-Z]+$': 'ALLOW'
'^/': 'DENY'
```
becomes after normalization:
```
array(2) {
["^/[a_zA_Z]+$"]=>
array(1) {
["header"]=>
string(5) "ALLOW"
}
["^/"]=>
array(1) {
["header"]=>
string(4) "DENY"
}
}
```
This patch fixes this behavior
> Fix normalization for URLs containing dash and no underscore

- Resources/config/clickjacking.yml
- Resources/config/content_type.yml
- Resources/config/encrypted_cookie.yml
- Resources/config/external_redirects.yml
- Resources/config/signed_cookie.yml
Scopes are not supported anymore in Symfony 3. This bundle declares services scoped to the "request" service. However, I don't see any dependency on request in any of them.
I don't think I'm wrong, anyway, I'd love a review by @stof :)
Thanks a lot
> Remove scope property from services that does not use it

- CHANGELOG.md
- ContentSecurityPolicy/DirectiveSet.php
- DependencyInjection/Configuration.php
- README.md
- Tests/ContentSecurityPolicy/DirectiveSetTest.php
- Tests/DependencyInjection/ConfigurationTest.php
This fixes a bug where we fallback on default-src whereas it's not a source-list (like plugin-types)
> Stronger directives definition, deprecate report-uri as array

- CHANGELOG.md
- DependencyInjection/Configuration.php
- Tests/ContentSecurityPolicy/DirectiveSetTest.php
- Tests/DependencyInjection/ConfigurationTest.php
According to the RFC, using multiple report-uri is valid. It reverts a part of my last changes on this topic
> Allow multiple report-uri

- CHANGELOG.md
- DependencyInjection/Compiler/UAParserCompilerPass.php
- DependencyInjection/Configuration.php
- DependencyInjection/NelmioSecurityExtension.php
- NelmioSecurityBundle.php
- README.md
- Resources/config/csp.yml
- Resources/config/csp_legacy.yml
- Tests/ContentSecurityPolicy/DirectiveSetTest.php
- Tests/DependencyInjection/ConfigurationTest.php
- UserAgent/UAFamilyParser/DoctrineCacheUAFamilyParser.php
- UserAgent/UAFamilyParser/PsrCacheUAFamilyParser.php
- UserAgent/UAFamilyParser/UAFamilyParser.php
- UserAgent/UAFamilyParser/UAFamilyParserInterface.php
- UserAgent/UserAgentParser.php
- composer.json
While using this browser_adaptive feature, I realized it consumes quite a lot of CPU. 
This PR decouple analyzer and parser so that cache can be used
> Decouple UA analyzer and parser to allow caching

- DependencyInjection/Configuration.php
- DependencyInjection/NelmioSecurityExtension.php
- EventListener/ReferrerPolicyListener.php
- README.md
- Resources/config/referrer_policy.yml
- Tests/DependencyInjection/ConfigurationTest.php
- Tests/Listener/ReferrerPolicyListenerTest.php
| Q | A |
| --- | --- |
| Branch? | `master` |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
Documentation: https://www.w3.org/TR/referrer-policy/
Even it is  working draft, some browsers has already implemented the specification:
- Chrome - currently supports [older version](https://www.w3.org/TR/2016/WD-referrer-policy-20160601/) of the draft [without the `same-origin`,`strict-origin`,`strict-origin-when-cross-origin` policies since version 56](https://www.chromestatus.com/feature/5639972996513792)
- Firefox - currently supports [older version](https://www.w3.org/TR/2016/WD-referrer-policy-20160601/) of the draft [without the `same-origin`,`strict-origin`,`strict-origin-when-cross-origin` …
> Add support for Referrer Policy

- CHANGELOG.md
- EventListener/ContentSecurityPolicyListener.php
- README.md
- Tests/Listener/ContentSecurityPolicyListenerTest.php
- Twig/NelmioCSPTwigExtension.php
- composer.json
At the moment, it's not possible to generate a nonce only for the `script-src` directive. Once a nonce is generated, it's added to both `script-src` and `style-src` directives. 
At the moment it prevents using `unsafe-inline`for `style-src` directive while the `script-src` directive uses a nonce.
This PR solves this issue
> Add $usage argument when generating a nonce

- EventListener/ExternalRedirectListener.php
- Tests/Listener/ExternalRedirectListenerTest.php
Seams like url like "\nhttp://www.google.fr" or "\0http://www.google.fr", pass through the external redirect filter, because parse_url() parse the host as path instead of host+protocol.
```
ExternalRedirectListener.php on line 76:
"\rhttp://www.google.fr?foo=1"
```
parse url =>
```
ExternalRedirectListener.php on line 127:
array:2 [▼
"path" => "_http://www.google.fr"
"query" => "foo=1"
]
```
If I provide url in query params like "/my/route?redirect=%0Dhttp://badwebsite.com", you can pass through the external redirect filter.
Maybe just providing a trim($url) like in this PR can fix the majority of the issues.
> Ensure intentionally prefixed external urls to pass through filters

- DependencyInjection/Configuration.php
- DependencyInjection/NelmioSecurityExtension.php
- EventListener/ForcedSslListener.php
- Resources/config/forced_ssl.yml
- Tests/Listener/ForcedSslListenerTest.php
Before this PR the bundle always used the default http status code `302` of the `Symfony\Component\HttpFoundation\RedirectResponse` class.
This PR adds the possibility to change that status code to something else, like so:
```
nelmio_security:
forced_ssl:
redirect_status_code: 301
```
> Forced SSL configurable redirect status code

- EventListener/ForcedSslListener.php
- Tests/Listener/ForcedSslListenerTest.php
| Q | A |
| --- | --- |
| Branch? | "master" |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #147 |
| License | MIT |
> Skip setting Strict-Transport-Security header for none-secure requests

- EventListener/ClickjackingListener.php
- Tests/Listener/ClickjackingListenerTest.php
Allows matching the query parameter for clickjacking protection.
> Use request URI instead of path info

- Controller/ContentSecurityPolicyController.php
Correct the name of class expected as 3rd argument in `ContentSecurityPolicyController::__construct`
> Deprecation message reflects correct class name

- README.md
According to https://hstspreload.org/ which is what the old http://hstspreload.appspot.com/ redirects to a max age of 1 year is required.
Also according to http://caniuse.com/#feat=stricttransportsecurity almost all browsers support it now.
> HSTS requires max age of at least 1 year

- DependencyInjection/Compiler/CspReportFilterCompilerPass.php
- Tests/DependencyInjection/CspReportFilterCompilerPassTest.php
When csp enabled is set to false in the configuration csp.xml will not be loaded,
so there is no service `nelmio_security.csp_report.filter` and asking the definition
for that non-existing service results in an exception.
So first we check if the service is available in the container and if it's not we bail out
(return early).
Fixes https://github.com/nelmio/NelmioSecurityBundle/issues/174
> Abort CSP compiler pass when CSP is not enabled

- composer.json
v9.99.99 of random_compat is a no-op library specifically for PHP7.
> Support random_compat v9.99.99

- .gitattributes
This PR adds `.gitattributes`, which can be used to control which files are being shipped with distribution installs via Composer.
This will prevent Composer from downloading files which are not needed when used as a dependencies: CI files and tests.
> Don't ship unneeded files for composer installs

- DependencyInjection/Configuration.php
- EventListener/XssProtectionListener.php
- Tests/DependencyInjection/ConfigurationTest.php
- Tests/Listener/XssProtectionListenerTest.php
`X-XSS-Protection` supports specifying a reporting endpoint. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
> Allow configuring a report URI for XSS

- ContentSecurityPolicy/NonceGenerator.php
This is how the standard defines the nonce
```
; Nonces: 'nonce-[nonce goes here]'
nonce-source  = "'nonce-" base64-value "'"
base64-value  = 1*( ALPHA / DIGIT / "+" / "/" / "-" / "_" )*2( "=" )
```
So let’s use base64 for nonce encoding.
> Use base64 for encoding

- EventListener/ExternalRedirectListener.php
- Session/CookieSessionHandler.php
I don't know if it was left out or what but I guess this was incorrect use of logger interface. I mean, these classes typehint `Psr\Log\LoggerInterface` so there are no `warn` or `crit` methods there, they were in Symfony's bridge. But the typehint is for PSR so... it should be `warning` and `critical`, right?
> Fixed deprecated/invalid method usage on logger interface

- ContentSecurityPolicy/ShaComputer.php
This uses possessive quantifiers whenever possible, to prevent useless backtracking.
Note that PCRE might be smart enough to guess these automatically (these are all cases of a repetition of chars followed by a char not allowed by the repetition), but I'm not sure it actually does such optimization automatically today. So this forces the optimization to be applied.
> Optimize regular expressions in the sha computer

- README.md
Not specifying the usage of the nonce is deprecated, so the readme should provide the usage when documenting the Twig function.
> show non-deprecated usage of the csp_nonce Twig function

- composer.json
Hi, 
Apparently `paragonie/random_compat` `9.99.100` was released and now this package can't be installed any longer: 
```bash
$ composer require nelmio/security-bundle
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.
Using …
```
> Allow installation alongside `paragonie/random_compat` `9.99.100`

- ContentSecurityPolicy/Violation/Event.php
- Tests/ContentSecurityPolicy/Violation/EventTest.php
* The Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Event class extends
from the Symfony\Component\EventDispatcher\Event class. This class has been removed
and needs to be replaced with Symfony\Contracts\EventDispatcher
* In the ContentSecurityPolicyController the event dispatcher has a different signature
starting from version 4.3. Keep this version in mind to switch the argument list
I'm not using the LegacyEventDispatcherProxy because this will be deprecated in Symfony 5 this method signature changes again.
> Fix the ClassNotFoundError Exception

- ContentSecurityPolicy/ContentSecurityPolicyParser.php
See https://w3c.github.io/webappsec-csp/#directive-script-src
`wasm-unsafe-eval` is more specific than `unsafe-eval`, by allowing only APIs that can evaluate WebAssembly but not APIs that can evaluate JS (`unsafe-eval` allows both)
> Add the wasm-unsafe-eval keyword for CSP

- src/EventListener/ClickjackingListener.php
- src/EventListener/ContentSecurityPolicyListener.php
- src/EventListener/ContentTypeListener.php
- src/EventListener/ExternalRedirectListener.php
- src/EventListener/FlexibleSslListener.php
- src/EventListener/ForcedSslListener.php
- src/EventListener/ReferrerPolicyListener.php
- src/EventListener/SignedCookieListener.php
- src/EventListener/XssProtectionListener.php
- src/Session/CookieSessionHandler.php
- tests/Listener/ClickjackingListenerTest.php
- tests/Listener/ContentSecurityPolicyListenerTest.php
- tests/Listener/ContentTypeListenerTest.php
- tests/Listener/ExternalRedirectListenerTest.php
- tests/Listener/FlexibleSslListenerTest.php
- tests/Listener/ForcedSslListenerTest.php
- tests/Listener/ReferrerPolicyListenerTest.php
- tests/Listener/SignedCookieListenerTest.php
- tests/Listener/XssProtectionListenerTest.php
- tests/Session/CookieSessionHandlerTest.php
They were added in Symfony 4.4
Ref: https://symfony.com/doc/4.4/components/http_kernel.html#creating-an-event-listener
> Use RequestEvent and ResponseEvent

- ContentSecurityPolicy/Violation/Filter/BrowserBugsNoiseDetector.php
- ContentSecurityPolicy/Violation/Log/Logger.php
- ContentSecurityPolicy/Violation/Report.php
- Filter moz-extension reports as they all look bogus
- Log user agent as well as CSP report data when logging CSP violations, which may help identify buggy browser patterns
> Various CSP reporting improvements

- phpstan-baseline.neon
- phpstan.neon.dist
- src/ContentSecurityPolicy/DirectiveSet.php
- src/ContentSecurityPolicy/ShaComputer.php
- src/DependencyInjection/Compiler/UAParserCompilerPass.php
- src/DependencyInjection/NelmioSecurityExtension.php
- src/ExternalRedirect/WhitelistBasedTargetValidator.php
- tests/Functional/ContentSecurityPolicyTest.php
- tests/Listener/ContentSecurityPolicyListenerTest.php
- tests/Listener/FlexibleSslListenerTest.php
- tests/Listener/ForcedSslListenerTest.php
The ignored errors are because:
- `session_id()` and `session_name()` returning `string|false`.
- one related with https://github.com/phpstan/phpstan/discussions/6507
- The other one I'm not sure if in the signatures can be all the directives to be able to specify the array shape, I prefer to ignore it for now
After this there will be 14 errors left in level 8.
> Bump PHPStan to level 7

- phpstan-baseline.neon
- phpstan.neon.dist
- src/ContentSecurityPolicy/PolicyManager.php
- src/ContentSecurityPolicy/Violation/Filter/CustomRulesNoiseDetector.php
- src/DependencyInjection/NelmioSecurityExtension.php
- src/EventListener/AbstractContentTypeRestrictableListener.php
- src/EventListener/ExternalRedirectListener.php
- src/EventListener/FlexibleSslListener.php
- src/ExternalRedirect/WhitelistBasedTargetValidator.php
- src/Session/CookieSessionHandler.php
- tests/Listener/FlexibleSslListenerTest.php
With level 8 I think we are fine with the static analysis.
The ignored errors added are about `InputBag::get()` call returning `null` after calling `:InputBag:has()`, issue related to https://github.com/phpstan/phpstan-symfony/pull/250.
> Bump PHPStan level to 8

- composer.json
- phpstan-baseline.neon
- phpstan.neon.dist
- src/EventListener/ClickjackingListener.php
- src/EventListener/ContentSecurityPolicyListener.php
- src/EventListener/ContentTypeListener.php
- src/EventListener/ExternalRedirectListener.php
- src/EventListener/FlexibleSslListener.php
- src/EventListener/ForcedSslListener.php
- src/EventListener/KernelEventForwardCompatibilityTrait.php
- src/EventListener/ReferrerPolicyListener.php
- src/EventListener/SignedCookieListener.php
- src/EventListener/XssProtectionListener.php
- src/Session/CookieSessionHandler.php
- tests/Listener/ClickjackingListenerTest.php
- tests/Listener/ContentSecurityPolicyListenerTest.php
- tests/Listener/ContentTypeListenerTest.php
- tests/Listener/ExternalRedirectListenerTest.php
- tests/Listener/FlexibleSslListenerTest.php
- tests/Listener/ForcedSslListenerTest.php
- tests/Listener/ListenerTestCase.php
- tests/Listener/ReferrerPolicyListenerTest.php
- tests/Listener/SignedCookieListenerTest.php
- tests/Listener/XssProtectionListenerTest.php
- tests/Session/CookieSessionHandlerTest.php
Uses the same strategy as https://github.com/getsentry/sentry-symfony/blob/dd37786fc7ca81a4320e6d9812ff549104193043/src/EventListener/KernelEventForwardCompatibilityTrait.php
> Add PHPStan deprecation rules

- CHANGELOG.md
- ContentSecurityPolicy/Violation/Event.php
- ContentSecurityPolicy/Violation/ReportEvent.php
- Controller/ContentSecurityPolicyController.php
- DependencyInjection/NelmioSecurityExtension.php
- NelmioSecurityBundle.php
- Tests/ContentSecurityPolicy/Violation/ReportEventTest.php
I think the name is better, instead of doing it directly in 3.0, deprecating `Event` would allow users to have a smooth upgrade path.
> Rename `Event` to `ReportEvent`

- src/EventListener/FlexibleSslListener.php
- tests/Listener/FlexibleSslListenerTest.php
This way we can remove the method when dropping support for Symfony 4.4.
I was thinking about if listeners in general should be `internal` since the user shouldn't interact with them directly 🤔
> Mark FlexibleSslListener::logout() as internal

- README.md
- src/EventListener/ContentSecurityPolicyListener.php
I've reverted the `@internal` annotation on `ContentSecurityPolicyListener` since they can be use without Twig as indicated in docs.
> Update installation docs

- src/EventListener/ContentSecurityPolicyListener.php
- tests/Listener/ContentSecurityPolicyListenerTest.php
We have a case where we already configure a CSP header on the response, and then the bundle is overwriting it, which is not great IMO.
> Avoid CSP header overwrite

- src/Resources/doc/index.rst
The docs of this bundle are now online: https://symfony.com/bundles/NelmioSecurityBundle/current/index.html
I spotted some minor syntax issues and this PR fixes them. Thanks!
If you ever need help with RST syntax _(which feels a bit strict when you start using it)_ please ping me and I'll be happy to help.
-----
A note for people not used to RST syntax. Code blocks are usually defined like this:
```rst
.. code-block:: php
// ...
```
However, since PHP examples are so common in Symfony Docs, we use a trick which consists of this:
```rst
Any normal text here, like a paragraph::
// ... PHP code here
More normal text here [...]
```
The two `::` at the end of any text means that the following indented content is a PHP code block.
> [Doc] Fix some syntax issues

- src/ContentSecurityPolicy/Violation/Filter/BrowserBugsNoiseDetector.php
- tests/ContentSecurityPolicy/Violation/FilterTest.php
Firefox reports a CSP violation on the `view-source` view for any URL with a Content-Security-Policy directive for `default-src` or `style-src` (except `unsafe-inline` of course) - and also sends a CSP report to the `report-uri`. This PR filters any reports sent from `view-source` views.
> Filter `view-source` reports

- src/EventListener/ExternalRedirectListener.php
- src/ExternalRedirect/ExternalRedirectResponse.php
- src/Resources/doc/index.rst
- tests/Listener/ExternalRedirectListenerTest.php
Introduces `ExternalRedirectResponse` to allow redirects to other hosts without the need to configure those hosts globally allowing for more fine-grained control.
Fixes #330.
> Introduce `ExternalRedirectResponse`

- src/Twig/Node/CSPNode.php
This PR makes CSPNode compatible with twig 3.9.
Since https://github.com/twigphp/Twig/pull/3999 we cannot use `ob_` method to get the generated output (See https://github.com/twigphp/Twig/issues/4034)
This PR fixes the issue by using the CaptureNode introduced in https://github.com/twigphp/Twig/pull/3954
Fix #343
> Fix compatibility with twig 3.9 and yielding

- src/DependencyInjection/NelmioSecurityExtension.php
The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "Presta\SitemapBundle\DependencyInjection\PrestaSitemapExtension".
> Fix DI Extension class deprecation with Symfony 7.1

- src/DependencyInjection/Configuration.php
- src/DependencyInjection/NelmioSecurityExtension.php
- src/EventListener/SignedCookieListener.php
- src/Resources/config/signed_cookie.php
- src/Resources/doc/index.rst
- src/Signer.php
- src/Signer/SignerInterface.php
- tests/DependencyInjection/NelmioSecurityExtensionTest.php
- tests/Listener/SignedCookieListenerTest.php
- tests/SignerTest.php
The goal of this PR is to allow backward-compatible signed cookie `hash_algo` upgrades. With the current code any existing signed cookies would be rejected when the `hash_algo` is changed which makes upgrading to a more secure hashing algorithm tricky.
This PR addresses this by;
- including the used hash algorithm in the signed cookie value;
- introducing `legacy_hash_algo` to support a previously configured algorithm during verification.
This is a stepping stone to address #324 but does not yet fix it. Changing the `hash_algo` default value would still break any existing cookies that don't include the hash algorithm in their signed value yet; the `legacy_hash_algo` would need to be configured manually for them to keep working. I don't currently see a backward-compatible way to change the …
> Add `legacy_hash_algo` to support backward-compatible `hash_algo` changes

- src/DependencyInjection/Configuration.php
- src/DependencyInjection/NelmioSecurityExtension.php
- tests/DependencyInjection/NelmioSecurityExtensionTest.php
Deprecate the default value for the `signed_cookie.hash_algo` configuration value (currently "sha256") in preparation for a change in 4.0.
Relates to #324.
> Deprecate the default signed cookie algorithm

- src/DependencyInjection/Configuration.php
The removal of the default configuration values during [the deprecation of this feature](https://github.com/nelmio/NelmioSecurityBundle/pull/342/files#diff-ebe00144d6cecb5ca8a2860883e01147f42bbed2b12a3a7f44915908a4829faa) is not backward-compatible and breaks container building for application that do not explicitly set `report_uri`.
Since the feature is expected to continue to work during the deprecation period I think it is safest to restore the defaults.
> Restore deprecated XSS default configuration values

- .php-cs-fixer.dist.php
- phpstan.neon.dist
- src/ContentSecurityPolicy/ContentSecurityPolicyParser.php
- src/ContentSecurityPolicy/DirectiveSet.php
- src/ContentSecurityPolicy/ShaComputer.php
- src/DependencyInjection/Configuration.php
- src/ExternalRedirect/AllowListBasedTargetValidator.php
- src/Signer.php
- src/Twig/Node/CSPNode.php
- src/Twig/Version.php
- tests/App/AppKernel.php
- tests/Listener/ExternalRedirectListenerTest.php
Fixing: 
```
Since twig/twig 3.12: The "tag" constructor argument of the "Nelmio\SecurityBundle\Twig\Node\CSPNode" class is deprecated and ignored (check which TokenParser class set it to "cspscript"), the tag is now automatically set by the Parser when needed. 
```
> Fix that passing a tag to twig nodes is deprecated since twig 3.12

- src/ContentSecurityPolicy/DirectiveSet.php
- src/ContentSecurityPolicy/PolicyManager.php
- src/DependencyInjection/Configuration.php
- src/Resources/doc/index.rst
- tests/ContentSecurityPolicy/DirectiveSetTest.php
This PR extends `DirectiveSet` with the [`report-to` directive](https://w3c.github.io/webappsec-csp/#directive-report-to). It is part of CSP Level 3 and intended to replace the deprecated [`report-uri` directive](https://w3c.github.io/webappsec-csp/#directive-report-uri).
The `report-to` directive works with reporting endpoints (from [Reporting](https://www.w3.org/TR/reporting-1/)). The endpoints need to be configured through another header (`Reporting-Endpoints`, [previously `Report-To`](https://www.w3.org/TR/2018/WD-reporting-1-20180925/)). This PR only adds the CSP directive; this enables users to migrate to the new reporting API if they provide the endpoints (via a `Reporting-Endpoints` header) themselves.
I did not deprecate the `report-uri` directive because browsers ignore it when …
> Add support for the `report-to` directive

- src/ContentSecurityPolicy/ConfigurationDirectiveSetBuilder.php
- src/ContentSecurityPolicy/DirectiveSetBuilderInterface.php
- src/ContentSecurityPolicy/LegacyDirectiveSetBuilder.php
- src/DependencyInjection/NelmioSecurityExtension.php
- src/EventListener/ContentSecurityPolicyListener.php
- tests/Listener/ContentSecurityPolicyListenerTest.php
- tests/Twig/IntegrationTest.php
This PR introduces the `DirectiveSetBuilderInterface` and the default implementation` ConfigurationDirectiveSetBuilder` proposed in #347, to allow for runtime modification of the CSP directive sets. The major changes are:
- Introduction of `DirectiveSetBuilderInterface` and `ConfigurationDirectiveSetBuilder`;
- The `ContentSecurityPolicyListener` constructor now takes `DirectiveSetBuilderInterface` instead of the directive sets directly;
- Changes to `NelmioSecurityExtension` to provide the configuration to the `ConfigurationDirectiveSetBuilder`s, which in turn are injected into `ContentSecurityPolicyListener` (instead of the directive sets).
This adds a layer between the configuration (and the directive sets built from it) and `ContentSecurityPolicyListener`. This layer provides an …
> Introduce `DirectiveSetBuilderInterface` to allow runtime modification
